load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "core",
    deps = [
        "//core/types",
        "//core/graph",
        "//core/storage",
    ],
    includes = ["include"],
)