name: Docker Build

on:
  push:
    branches: [ master ]
    paths:
      - 'dev/docker/Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
      - 'dev/docker/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and cache Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dev/docker/Dockerfile
          tags: dev-env:latest
          outputs: type=docker,dest=/tmp/dev-env.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: dev-env-image
          path: /tmp/dev-env.tar
