version: '3.8'

services:
  dev:
    build:
      context: ../..
      dockerfile: dev/docker/Dockerfile
    volumes:
      - ../..:/workspace:cached
      - ~/.gitconfig:/home/developer/.gitconfig:ro
      - /mnt/remote-storage:/mnt/remote-storage
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/developer/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/home/developer/.Xauthority
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    network_mode: host
    command: sleep infinity
    user: developer
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
