version: '3.8'

services:
  dev:
    build:
      context: ../..
      dockerfile: dev/docker/Dockerfile
    volumes:
      - ../..:/workspace:cached
      - ~/.gitconfig:/home/developer/.gitconfig:ro
      - /mnt/remote-storage:/mnt/remote-storage
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/developer/.Xauthority
      # - /run/user/$(id -u):/tmp/runtime-developer
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/home/developer/.Xauthority
      - NVIDIA_DRIVER_CAPABILITIES=all
      - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
      # Force software rendering for now
      - LIBGL_ALWAYS_SOFTWARE=1
      - DISABLE_VULKAN=1
      # Create XDG_RUNTIME_DIR in tmp
      - XDG_RUNTIME_DIR=/tmp/runtime-${USER}
      # Add these new variables to force software rendering
      - RERUN_PREFER_OPENGL=1  # Try to prefer OpenGL over Vulkan
      - __GLX_VENDOR_LIBRARY_NAME=mesa  # Force Mesa software rendering
      - MESA_GL_VERSION_OVERRIDE=3.3
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    network_mode: host
    command: sleep infinity
    user: developer
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    entrypoint: >
      /bin/bash -c "
        mkdir -p /tmp/runtime-${USER} &&
        chmod 700 /tmp/runtime-${USER} &&
        exec sleep infinity
      "
